# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e9bf1a8b53d7d1df7f38b09de2ea64604f5124d3df4f6487a0df46f306425aa0123153cb4c8c6a9a6c4b0881a125f9ba732bd52777107fcafa03ad5fd1edfb9

staging:
  secret_key_base: 2e9bf1a8b53d7d1df7f38b09de2ea64604f5124d3df4f6487a0df46f306425aa0123153cb4c8c6a9a6c4b0881a125f9ba732bd52777107fcafa03ad5fd1edfb9

test:
  secret_key_base: 4e19358c70e3181687bfd78ac889281b60988304092cc363ff411255920b5e4161f0468c75d93f19c79c10c7aa49911a5aacaeab8f921d443b41b09059f6a596

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
