---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: staging
  domain: artisticribbon.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: haproxy
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: passenger
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: apache
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mysql
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mysql_master
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  instance_id: i-78545199
  image_type: t2.medium
  image_id: ami-0745d26e
  security_groups:
  - default
  - web
  external_host: ec2-54-174-28-224.compute-1.amazonaws.com
  external_ip: 54.174.28.224
  internal_host: ip-172-31-53-157.ec2.internal
  internal_ip: 172.31.53.157
  zone: us-east-1a
  provider: aws
  platform: linux
  root_device_type: ebs
  static_ip: 54.174.28.224
  volumes:
  - vol-fa214be2
- volumes:
    staging_/dev/sdh: vol-fa214be2
  static_ips:
    staging: 54.174.28.224
